export const REVIEW_FETCH = 'REVIEW_FETCH';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const FETCH_SUCCESS_AGAIN = 'FETCH_SUCCESS_AGAIN';
export const SUBMIT_REVIEW_START = 'SUBMIT_REVIEW_START';
export const SUBMIT_REVIEW_SUCCESS = 'SUBMIT_REVIEW_SUCCESS';
export const SUBMIT_REVIEW_ERROR = 'SUBMIT_REVIEW_ERROR';

export const CLEAR_ALL = 'CLEAR_ALL';
